<a href="https://colab.research.google.com/github/anand-therattil/machine_learning/blob/main/pytorch_deeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

I have created this colab notebook to learn the deep learning using [PyTorch by Partrick Loeber](https://youtu.be/exaWOE8jvy8?si=AGBT7Nr61MBT9nhW)

Installation of pytorch in google colab can be done using ``` !pip install torch ```

To check if the pytorch is installed run this if there are no Error then the pytorch is installed successfully
Else go the https://pytorch.org/

In [ ]:
import torch
torch.cuda.is_available()  # to check if cuda/ GPU is available if False then cuda is not present True if present

False

Basic Defining

In [ ]:
# Random tensor
# torch.rand(dimension,dtype )
x = torch.rand(3)
print(x)

# Empty tensor
# torch.empty(dimension,dtype)
# Here empty tensor means there will be a value however it will in the value ranged in e^-10 (depends on the system )
x = torch.empty(1,2)
print(x)

# Ones tensor
# torch.ones(dimension,dtype)
x = torch.ones(1,4)
print(x)

# to check the size of a tensor we can use the x.size()
print(x.size())


tensor([0.7581, 0.4986, 0.0113])
tensor([[0., 0.]])
tensor([[1., 1., 1., 1.]])
torch.Size([1, 4])


Basic Operations
1. I have show for addition similar can be applicable for the
subtraction, multiplication, division and modulus.
2. Reshaping of the tensor using the ``` view()```

In [ ]:
x = torch.rand(2,2)
y = torch.ones(2,2)

print(x+y)
# Or
print(torch.add(x,y))


# Inplace Operation
y.add_(x) # Inplace addition
print(y)

# Reshaping of the tensor vector
# Keep in mind that while reshaping the present dimension should match with the current dimension
# However if the dimension is set as -1 the object automotically defines it
print(y.view(4,1))
print(y.view(-1,4))
print(y.view(4,-1))

tensor([[1.9123, 1.2155],
        [1.7478, 1.0974]])
tensor([[1.9123, 1.2155],
        [1.7478, 1.0974]])
tensor([[1.9123, 1.2155],
        [1.7478, 1.0974]])
tensor([[1.9123],
        [1.2155],
        [1.7478],
        [1.0974]])
tensor([[1.9123, 1.2155, 1.7478, 1.0974]])
tensor([[1.9123],
        [1.2155],
        [1.7478],
        [1.0974]])


Conversion to Numpy and vice versa

In [ ]:
import numpy as np
a = torch.rand(3,3)
b = a.numpy()
print(type(a))
print(type(b))
# However in this approach the if the value of a changes the value of b changes

a = torch.rand(3,3)
b = torch.from_numpy(a.numpy())
print(type(a))
print(type(b))

# In this the one the tensor are the cpu tensor however if the tensor is on the GPU then need to convert to cpu first then can be used for the for the numpy
if torch.cuda.is_available():
  device = torch.device("cuda")
else:
  device = torch.device("cpu")
a.to(device)
z =a + b
z.to("cpu") # To make it back  to normal tensor
z = torch.from_numpy(z.numpy())
z = z.numpy()


<class 'torch.Tensor'>
<class 'numpy.ndarray'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>


Calculation of Gradient through Backwards Propogation

In [ ]:
x = torch.rand(3,requires_grad =True)
print(x)

y = x + 2
print(y)

z = y*y*2
print(z)
# z = z.sum()
z.backward(torch.tensor([1,1,3]))

print(x.grad)

tensor([0.1230, 0.5288, 0.7583], requires_grad=True)
tensor([2.1230, 2.5288, 2.7583], grad_fn=<AddBackward0>)
tensor([ 9.0140, 12.7896, 15.2160], grad_fn=<MulBackward0>)
tensor([ 8.4919, 10.1152, 33.0992])


In [ ]:
x = torch.rand(3,requires_grad =True)
print(x)

y = x.detach() + 2
print(y)

z = y*y*2
print(z)
# z = z.sum()
# z.backward(torch.tensor([1,1,3]))

print(x.grad)

tensor([0.8013, 0.3743, 0.1006], requires_grad=True)
tensor([2.8013, 2.3743, 2.1006])
tensor([15.6944, 11.2744,  8.8247])
None


In [ ]:
weights = torch.ones(4,requires_grad=True)
print(weights)

for i in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([1., 1., 1., 1.], requires_grad=True)
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
weights = torch.ones(4,requires_grad=True)
print(weights)

for i in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([1., 1., 1., 1.], requires_grad=True)
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
import torch
import torch.nn as nn

X = torch.tensor([[1],[2],[3],[4]], dtype= torch.float32)
Y = torch.tensor([[2],[4],[6],[8]], dtype= torch.float32)

n_samples, n_features = X.shape
print(n_samples, n_features)
input_size, output_size  = n_features, n_features
model = nn.Linear(input_size,output_size)

learning_rate = 0.01
n_iters = 100
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr= learning_rate)

for epoch in range(n_iters):
  y_pred = model(X)

  l = loss(Y, y_pred)

  l.backward()

  optimizer.step()

  optimizer.zero_grad()

  if(epoch %10 ==0):
    [w,b] = model.parameters()
    print('epoch: '+str(epoch+1)+ " w:" +str(w)+" loss: "+str(l))




4 1
epoch: 1 w:Parameter containing:
tensor([[0.4791]], requires_grad=True) loss: tensor(28.2055, grad_fn=<MseLossBackward0>)
epoch: 11 w:Parameter containing:
tensor([[1.6973]], requires_grad=True) loss: tensor(0.7366, grad_fn=<MseLossBackward0>)
epoch: 21 w:Parameter containing:
tensor([[1.8950]], requires_grad=True) loss: tensor(0.0255, grad_fn=<MseLossBackward0>)
epoch: 31 w:Parameter containing:
tensor([[1.9285]], requires_grad=True) loss: tensor(0.0067, grad_fn=<MseLossBackward0>)
epoch: 41 w:Parameter containing:
tensor([[1.9355]], requires_grad=True) loss: tensor(0.0059, grad_fn=<MseLossBackward0>)
epoch: 51 w:Parameter containing:
tensor([[1.9381]], requires_grad=True) loss: tensor(0.0055, grad_fn=<MseLossBackward0>)
epoch: 61 w:Parameter containing:
tensor([[1.9401]], requires_grad=True) loss: tensor(0.0052, grad_fn=<MseLossBackward0>)
epoch: 71 w:Parameter containing:
tensor([[1.9419]], requires_grad=True) loss: tensor(0.0049, grad_fn=<MseLossBackward0>)
epoch: 81 w:Paramete

In [ ]:
import torch
import torch.nn as nn

X = torch.tensor([[1],[2],[3],[4]], dtype= torch.float32)
Y = torch.tensor([[2],[4],[6],[8]], dtype= torch.float32)

n_samples, n_features = X.shape
print(n_samples, n_features)
input_size, output_size  = n_features, n_features

class LinearRegression(nn.Module):
  def __init__(self, input_dim, output_dim):
    super(LinearRegression, self).__init__()
    self.lin = nn.Linear(input_dim, output_dim)

  def forward(self,x):
    return self.lin(x)

model = LinearRegression(input_size, output_size)

learning_rate = 0.01
n_iters = 100
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr= learning_rate)

for epoch in range(n_iters):
  y_pred = model(X)

  l = loss(Y, y_pred)

  l.backward()

  optimizer.step()

  optimizer.zero_grad()

  if(epoch %10 ==0):
    [w,b] = model.parameters()
    print('epoch: '+str(epoch+1)+ " w:" +str(w)+" loss: "+str(l))


In [ ]:
# Linear Regression
# Making the model
# Defining the Loss function, Optimizer
# Plotting of Data

import torch
import torch.nn as nn
import numpy   as np
from   sklearn import datasets
import matplotlib.pyplot as plt

X_numpy, y_numpy = datasets.make_regression(n_samples=100,n_features=1, noise=30, random_state=2)

X = torch.from_numpy(X_numpy.astype(np.float32))
y = torch.from_numpy(y_numpy.astype(np.float32))
y = y.view(y.shape[0], 1)  # This step is important as it converts the data in thr ([[a],[b]]) format


n_samples, n_features = X.shape
input_size = n_features
output_size = 1
print(n_features)
model = nn.Linear(input_size, output_size)

learning_rate = 0.01
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

num_epochs = 100
for epoch in range(num_epochs):
  y_pred = model(X)
  loss = criterion(y_pred,y)

  loss.backward()
  optimizer.step()

  optimizer.zero_grad()

  if(epoch%10==0):
    print(loss)


y_pred = model(X).detach().numpy()
plt.plot(X_numpy,y_numpy, 'ro')
plt.plot(X_numpy,y_pred, 'b')
plt.show()



In [ ]:
import torch
import torch.nn as nn
import numpy   as np
from   sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

total_data = datasets.load_breast_cancer()
data, target = total_data.data, total_data.target
target = np.array(target)
target = target.reshape(target.shape[0], 1)
n_samples, n_features = data.shape
print(target.shape)
print(n_samples, n_features)

X_train, X_test, y_train, y_test = train_test_split(data,target, test_size = 0.2, random_state=2)

Scaler = StandardScaler()
X_train = Scaler.fit_transform(X_train)
X_test = Scaler.fit_transform(X_test)

X_train = torch.from_numpy(X_train.astype(np.float32))
y_train = torch.from_numpy(y_train.astype(np.float32))

X_test = torch.from_numpy(X_test.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

class Logistic_Regression(nn.Module):
  def __init__(self, n_features):
    super(Logistic_Regression, self).__init__()
    self.Linear = nn.Linear(n_features, 1)

  def forward(self,x):
    y_predicted = torch.sigmoid(self.Linear(x))
    return y_predicted

model = Logistic_Regression(n_features)

learning_rate = 0.01
criterion = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

num_epochs = 100
for epoch in range(num_epochs):
  y_pred = model(X_train)
  loss = criterion(y_pred,y_train)

  loss.backward()
  optimizer.step()

  optimizer.zero_grad()

  if(epoch%10==0):
    print(loss)





(569, 1)
569 30
torch.Size([455, 30])
torch.Size([455, 1])
torch.Size([114, 30])
torch.Size([114, 1])
tensor(0.9592, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.6938, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.5455, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4592, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.4035, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.3642, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.3346, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.3114, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.2926, grad_fn=<BinaryCrossEntropyBackward0>)
tensor(0.2770, grad_fn=<BinaryCrossEntropyBackward0>)


In [ ]:
with torch.no_grad():
  y_pred = model(X_test)
  y_pred = y_pred.round()

  acc = y_pred.eq(y_test).sum()/float(y_test.shape[0]) *100
  print(acc)


tensor(95.6140)


In [3]:
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

input_size = 784 # 28X28 size
hidden_size = 100
num_classes = 10
num_epochs = 2
batch_size = 100
learning_rate = 0.001

train_dataset = torchvision.datasets.MNIST(root='./data',
                                           train=True,
                                           download=True,
                                           transform=transforms.ToTensor())


test_dataset = torchvision.datasets.MNIST(root='./data',
                                           train=False,
                                           download=True,
                                           transform=transforms.ToTensor())

train_loader = torch.utils.data.DataLoader(dataset= train_dataset,
                                       batch_size=batch_size,
                                       shuffle=True)

test_loader = torch.utils.data.DataLoader(dataset= test_dataset,
                                       batch_size=batch_size,
                                       shuffle=True)

examples= iter(train_loader)
samples, labels = examples.__next__()
print(samples.shape, labels.shape)


class NeuralNet(nn.Module):
  def __init__(self,input_size,hidden_size, num_classes):
    super(NeuralNet, self).__init__()
    self.l1 = nn.Linear(input_size,hidden_size)
    self.relu = nn.ReLU()
    self.l2 = nn.Linear(hidden_size,num_classes)

  def forward(self, x):
    out = self.l1(x)
    out = self.relu(out)
    out = self.l2(out)
    return out



model = NeuralNet(input_size, hidden_size, num_classes)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

n_total_steps = len(train_loader)

for epoch in range(num_epochs):
  for i, (images, labels) in enumerate(train_loader):
    images = images.reshape(-1, 28*28).to(device)
    labels = labels.to(device)


    output = model(images)
    loss = criterion(output, labels)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (i+1)%100 ==0:
      print(f'epoch {epoch+1} / {num_epochs,}, step {i+1}/n_total_steps, loss={loss.item()}')

with  torch.no_grad():
  n_correct = 0
  n_samples = 0
  for images, labels in test_loader:
    images = images.reshape(-1, 28*28).to(device)
    labels = labels.to(device)
    outputs = model(images)

    _, predictions = torch.max(outputs, 1)
    n_samples += labels.shape[0]

    n_correct += (predictions == labels).sum().item()

acc = 100 * n_correct /n_samples

print(f'the accuracy ={acc}')


torch.Size([100, 1, 28, 28]) torch.Size([100])
epoch 1 / (2,), step 100/n_total_steps, loss=0.3988817632198334
epoch 1 / (2,), step 200/n_total_steps, loss=0.29275989532470703
epoch 1 / (2,), step 300/n_total_steps, loss=0.25011056661605835
epoch 1 / (2,), step 400/n_total_steps, loss=0.3486343324184418
epoch 1 / (2,), step 500/n_total_steps, loss=0.21388429403305054
epoch 1 / (2,), step 600/n_total_steps, loss=0.22305843234062195
epoch 2 / (2,), step 100/n_total_steps, loss=0.17536517977714539
epoch 2 / (2,), step 200/n_total_steps, loss=0.0817161574959755
epoch 2 / (2,), step 300/n_total_steps, loss=0.23464488983154297
epoch 2 / (2,), step 400/n_total_steps, loss=0.25027403235435486
epoch 2 / (2,), step 500/n_total_steps, loss=0.2893359065055847
epoch 2 / (2,), step 600/n_total_steps, loss=0.20310406386852264
the accuracy =95.11
